/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Medicamento;
import model.dao.MedicamentoDAO;

/**
 *
 * @author Raphael
 */
public class Queries2 extends javax.swing.JFrame {

    /**
     * Creates new form Queries2
     */
    public Queries2() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));
        
        //readJTable();
        
    }
    
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        MedicamentoDAO meddao = new MedicamentoDAO();
        
        for (Medicamento m: meddao.read()){
            
            modelo.addRow(new Object[]{
                m.getId_med(),
                m.getNome_med(),
                m.getPreco()
            });
            
        }
    }
    public void readJTableForNome(String Nome){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        MedicamentoDAO meddao = new MedicamentoDAO();
        
        for (Medicamento m: meddao.readForNome(Nome)){
            
            modelo.addRow(new Object[]{
               // m.getId_med(),
                m.getNome_med(),
                m.getDescr_prod(),
                m.getNome_tipo(),
                m.getSubstancias()
            });
            
        }
    }
    public void readJTableForPrincipio(String Prin){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        MedicamentoDAO meddao = new MedicamentoDAO();
        
        for (Medicamento m: meddao.readForPrincipio(Prin)){
            
            modelo.addRow(new Object[]{
              //  m.getId_med(),
                m.getNome_med(),
                m.getDescr_prod(),
                m.getNome_tipo(),
                m.getSubstancias()
            });
            
        }
    }
    public void readJTableForTipo(String Tipos){
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        MedicamentoDAO meddao = new MedicamentoDAO();
        
        for (Medicamento m: meddao.readForTipo(Tipos)){
            
            modelo.addRow(new Object[]{
              //  m.getId_med(),
                m.getNome_med(),
                m.getDescr_prod(),
                m.getNome_tipo(),
                m.getSubstancias()
            });
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        med_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        b_buscar = new javax.swing.JButton();
        tipo_pesquisa = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel1.setText("Pesquisa :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 90, 24);

        med_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_textActionPerformed(evt);
            }
        });
        getContentPane().add(med_text);
        med_text.setBounds(90, 50, 130, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Tipo", "Princípio Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 660, 260);

        b_buscar.setText("Buscar");
        b_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(b_buscar);
        b_buscar.setBounds(480, 50, 80, 30);

        tipo_pesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione modo de pesquisa>", "Nome medicamento", "Princípio ativo", "Tipo" }));
        tipo_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_pesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(tipo_pesquisa);
        tipo_pesquisa.setBounds(250, 50, 210, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(545, 521));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 50, 40, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ecoFarma");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, -10, 100, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 680, 380);

        setSize(new java.awt.Dimension(689, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscarActionPerformed
        // TODO add your handling code here:
        if (tipo_pesquisa.getSelectedItem().equals("<Selecione modo de pesquisa>")) {
            JOptionPane.showMessageDialog(null,"Selecione o modo de pesquisa",null, WIDTH);
        }
        else if (tipo_pesquisa.getSelectedItem().equals("Nome medicamento")) {
            readJTableForNome(med_text.getText());
        }
        else if (tipo_pesquisa.getSelectedItem().equals("Tipo")) {
            readJTableForTipo(med_text.getText());}
        else {
            readJTableForPrincipio(med_text.getText());
        }
        
    }//GEN-LAST:event_b_buscarActionPerformed

    private void tipo_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_pesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
telaprincipal tela = new telaprincipal();
tela.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void med_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Queries2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Queries2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Queries2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Queries2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Queries2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField med_text;
    private javax.swing.JComboBox tipo_pesquisa;
    // End of variables declaration//GEN-END:variables
}
