/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import javax.swing.JOptionPane;

/**
 *
 * @author thiag
 */
public class telalogin extends javax.swing.JFrame {

    /**
     * Creates new form telalogin
     */
    public telalogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAcessar = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();
        jLabelusuario = new javax.swing.JLabel();
        jLabelsenha = new javax.swing.JLabel();
        usuariofield = new javax.swing.JTextField();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jLabellogo = new javax.swing.JLabel();
        jLabelfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonAcessar.setText("Acessar");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(300, 150, 90, 30);

        jButtonsair.setText("sair");
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsair);
        jButtonsair.setBounds(390, 150, 90, 30);

        jLabelusuario.setText("Usuario:");
        getContentPane().add(jLabelusuario);
        jLabelusuario.setBounds(280, 54, 50, 20);

        jLabelsenha.setText("Senha:");
        getContentPane().add(jLabelsenha);
        jLabelsenha.setBounds(280, 84, 50, 20);

        usuariofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariofieldActionPerformed(evt);
            }
        });
        getContentPane().add(usuariofield);
        usuariofield.setBounds(330, 50, 150, 30);

        jPasswordFieldsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldsenha);
        jPasswordFieldsenha.setBounds(330, 80, 150, 30);

        jLabellogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eco.jpg"))); // NOI18N
        getContentPane().add(jLabellogo);
        jLabellogo.setBounds(0, 0, 290, 270);

        jLabelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundobranco.png"))); // NOI18N
        getContentPane().add(jLabelfundo);
        jLabelfundo.setBounds(0, 0, 500, 240);

        setSize(new java.awt.Dimension(513, 279));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
if(usuariofield.getText().equals("medico")&&jPasswordFieldsenha.getText().equals("193")){
 telaprincipal tela= new telaprincipal();
tela.setVisible(true);
dispose();}
else if(usuariofield.getText().equals("enfermeiro")&&jPasswordFieldsenha.getText().equals("192")){
 telaprincipal tela= new telaprincipal();
tela.setVisible(true);
dispose();}
else{JOptionPane.showMessageDialog(rootPane, "senha ou usuario invalidos");}
     
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
System.exit(0);                                              
       
    }//GEN-LAST:event_jButtonsairActionPerformed

    private void usuariofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariofieldActionPerformed

    private void jPasswordFieldsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telalogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JLabel jLabelfundo;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JLabel jLabelsenha;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JTextField usuariofield;
    // End of variables declaration//GEN-END:variables
}
