/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author thiag
 */
public class telaprincipal extends javax.swing.JFrame {
    
    public telaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jInternalFramebemvindo = new javax.swing.JInternalFrame();
        jPanelinternal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        painelfundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ferramenta = new javax.swing.JMenu();
        jMenuItemtelabemvindo = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenupesquisa = new javax.swing.JMenu();
        jMenuItempesquisa1 = new javax.swing.JMenuItem();
        jMenuItempesquisa2 = new javax.swing.JMenuItem();
        jMenuItempesquisa3 = new javax.swing.JMenuItem();
        jMenusair = new javax.swing.JMenu();
        jMenuItemsair = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jInternalFramebemvindo.setVisible(true);
        jInternalFramebemvindo.getContentPane().setLayout(null);

        jPanelinternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelinternal.setLayout(null);
        jInternalFramebemvindo.getContentPane().add(jPanelinternal);
        jPanelinternal.setBounds(0, 50, 670, 300);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundobranco.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 10, 10);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_medic.png"))); // NOI18N
        jButton1.setToolTipText("consulta para medico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 90, 110, 110);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 244, 244));
        jLabel2.setText("<html> <p> <center> Consulta </br> medicamentos </center> </p> </html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 110, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_paciente.jpeg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 90, 110, 110);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Cadastro paciente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 70, 120, 16);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ecoFarma");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, -10, 110, 50);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Receituário");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 70, 80, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_receita.jpeg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 90, 120, 110);

        painelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoprincipal.jpg"))); // NOI18N
        getContentPane().add(painelfundo);
        painelfundo.setBounds(0, -60, 1110, 550);

        ferramenta.setText("arquivo");

        jMenuItemtelabemvindo.setText("Receituário");
        jMenuItemtelabemvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemtelabemvindoActionPerformed(evt);
            }
        });
        ferramenta.add(jMenuItemtelabemvindo);

        jMenuItem2.setText("sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        ferramenta.add(jMenuItem2);

        jMenuBar1.add(ferramenta);

        jMenu3.setText("cadastro");

        jMenuItem1.setText("paciente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenupesquisa.setText("pesquisa");

        jMenuItempesquisa1.setText("consulta medicamentos");
        jMenuItempesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItempesquisa1ActionPerformed(evt);
            }
        });
        jMenupesquisa.add(jMenuItempesquisa1);

        jMenuItempesquisa2.setText("pesquisa2");
        jMenuItempesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItempesquisa2ActionPerformed(evt);
            }
        });
        jMenupesquisa.add(jMenuItempesquisa2);

        jMenuItempesquisa3.setText("pesquisa3");
        jMenupesquisa.add(jMenuItempesquisa3);

        jMenuBar1.add(jMenupesquisa);

        jMenusair.setText("Ajuda");

        jMenuItemsair.setText("Sobre");
        jMenuItemsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsairActionPerformed(evt);
            }
        });
        jMenusair.add(jMenuItemsair);

        jMenuBar1.add(jMenusair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(687, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItempesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItempesquisa1ActionPerformed
Queries2 tela = new Queries2();
tela.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItempesquisa1ActionPerformed

    private void jMenuItempesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItempesquisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItempesquisa2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Queries2 tela = new Queries2();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsairActionPerformed
      Sobre tela = new Sobre();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jMenuItemsairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
formupaciente tela = new formupaciente();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
formupaciente tela = new formupaciente();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItemtelabemvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemtelabemvindoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemtelabemvindoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaprincipal().setVisible(true);
            }
        });
    }

    void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ferramenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFramebemvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItempesquisa1;
    private javax.swing.JMenuItem jMenuItempesquisa2;
    private javax.swing.JMenuItem jMenuItempesquisa3;
    private javax.swing.JMenuItem jMenuItemsair;
    private javax.swing.JMenuItem jMenuItemtelabemvindo;
    private javax.swing.JMenu jMenupesquisa;
    private javax.swing.JMenu jMenusair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelinternal;
    private javax.swing.JLabel painelfundo;
    // End of variables declaration//GEN-END:variables
}
