/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author thiag
 */
public class telaprincipal extends javax.swing.JFrame {
    
    public telaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jInternalFramebemvindo = new javax.swing.JInternalFrame();
        jPanelinternal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        painelfundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fechartelaprincipal = new javax.swing.JButton();
        jLabelplanodefundotelaprincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenupesquisa = new javax.swing.JMenu();
        jMenuItempesquisa1 = new javax.swing.JMenuItem();
        jMenuItempesquisa2 = new javax.swing.JMenuItem();
        jMenuItempesquisa3 = new javax.swing.JMenuItem();
        ferramenta = new javax.swing.JMenu();
        jMenuItemtelabemvindo = new javax.swing.JMenuItem();
        jMenusair = new javax.swing.JMenu();
        jMenuItemsair = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFramebemvindo.setTitle("bem vindo");
        jInternalFramebemvindo.setVisible(true);
        jInternalFramebemvindo.getContentPane().setLayout(null);

        jPanelinternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelinternal.setLayout(null);

        jLabel2.setText("consulta-");
        jPanelinternal.add(jLabel2);
        jLabel2.setBounds(10, 4, 60, 20);

        jLabel3.setText("Cadastro paciente");
        jPanelinternal.add(jLabel3);
        jLabel3.setBounds(150, 10, 90, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadMedicos.png"))); // NOI18N
        jButton1.setToolTipText("consulta para medico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelinternal.add(jButton1);
        jButton1.setBounds(10, 30, 100, 120);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadPacientes.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelinternal.add(jButton2);
        jButton2.setBounds(130, 30, 100, 120);

        painelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/internalframe.png"))); // NOI18N
        jPanelinternal.add(painelfundo);
        painelfundo.setBounds(-240, 0, 940, 300);

        jInternalFramebemvindo.getContentPane().add(jPanelinternal);
        jPanelinternal.setBounds(0, 50, 670, 300);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("sistema de gerenciamento de:");
        jInternalFramebemvindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 240, 50);

        fechartelaprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        fechartelaprincipal.setToolTipText("fechar tela principal");
        fechartelaprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechartelaprincipalActionPerformed(evt);
            }
        });
        jInternalFramebemvindo.getContentPane().add(fechartelaprincipal);
        fechartelaprincipal.setBounds(620, 10, 30, 30);

        getContentPane().add(jInternalFramebemvindo);
        jInternalFramebemvindo.setBounds(0, 70, 680, 380);

        jLabelplanodefundotelaprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelplanodefundotelaprincipal);
        jLabelplanodefundotelaprincipal.setBounds(0, 0, 680, 450);

        jMenu3.setText("cadastro");

        jMenuItem1.setText("paciente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenupesquisa.setText("pesquisa");

        jMenuItempesquisa1.setText("pesquisa1");
        jMenuItempesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItempesquisa1ActionPerformed(evt);
            }
        });
        jMenupesquisa.add(jMenuItempesquisa1);

        jMenuItempesquisa2.setText("pesquisa2");
        jMenuItempesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItempesquisa2ActionPerformed(evt);
            }
        });
        jMenupesquisa.add(jMenuItempesquisa2);

        jMenuItempesquisa3.setText("pesquisa3");
        jMenupesquisa.add(jMenuItempesquisa3);

        jMenuBar1.add(jMenupesquisa);

        ferramenta.setText("ferramenta");

        jMenuItemtelabemvindo.setText("tela bem-vindo");
        ferramenta.add(jMenuItemtelabemvindo);

        jMenuBar1.add(ferramenta);

        jMenusair.setText("sair");

        jMenuItemsair.setText("sair");
        jMenuItemsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsairActionPerformed(evt);
            }
        });
        jMenusair.add(jMenuItemsair);

        jMenuBar1.add(jMenusair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(690, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItempesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItempesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItempesquisa1ActionPerformed

    private void jMenuItempesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItempesquisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItempesquisa2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Queries2 tela = new Queries2();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fechartelaprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechartelaprincipalActionPerformed
        jInternalFramebemvindo.dispose();
    }//GEN-LAST:event_fechartelaprincipalActionPerformed

    private void jMenuItemsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsairActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jMenuItemsairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
formupaciente tela = new formupaciente();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
formupaciente tela = new formupaciente();
tela.setVisible(true);
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaprincipal().setVisible(true);
            }
        });
    }

    void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fechartelaprincipal;
    private javax.swing.JMenu ferramenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFramebemvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelplanodefundotelaprincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItempesquisa1;
    private javax.swing.JMenuItem jMenuItempesquisa2;
    private javax.swing.JMenuItem jMenuItempesquisa3;
    private javax.swing.JMenuItem jMenuItemsair;
    private javax.swing.JMenuItem jMenuItemtelabemvindo;
    private javax.swing.JMenu jMenupesquisa;
    private javax.swing.JMenu jMenusair;
    private javax.swing.JPanel jPanelinternal;
    private javax.swing.JLabel painelfundo;
    // End of variables declaration//GEN-END:variables
}
